const API="";
const app=document.getElementById("app"),nav=document.getElementById("nav");
const token=()=>localStorage.getItem("token");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(msg){const d=document.createElement("div");d.className="toast";d.textContent=msg;document.getElementById("toast").append(d);setTimeout(()=>d.remove(),2500)}
async function api(path,opts={}){opts.headers={"Content-Type":"application/json",...(opts.headers||{})};if(token())opts.headers.Authorization="Bearer "+token();let r=await fetch(API+path,opts);let t=await r.text();let data=t?JSON.parse(t):null;if(!r.ok)throw new Error(data?.detail||"Request failed");return data}
function navBar(){nav.innerHTML=token()?`<a href="#home">Home</a><a href="#forms">Forms</a><button onclick="logout()">Sign out</button>`:`<a href="#signin">Sign in</a><a href="#signup">Sign up</a>`}
function logout(){localStorage.removeItem("token");location.hash="#signin"}
function shell(title,body){navBar();app.innerHTML=`<div class="container"><div class="between"><div><h1>${title}</h1></div></div>${body}</div>`}
function err(e){toast(e.message)}
function requireAuth(){if(!token()){location.hash="#signin";return false}return true}

function signup(){navBar();app.innerHTML=`<div class="auth card"><h1>Create account</h1><p class="muted">Signup</p><label>Full name</label><input id="name" class="input"><label>Email</label><input id="email" type="email" class="input"><label>Password</label><input id="pass" type="password" class="input"><button class="btn primary" onclick="doSignup()">Sign up</button><p>Already registered? <a href="#signin">Sign in</a></p><div id="error" class="error"></div></div>`}
async function doSignup(){try{await api("/auth/signup",{method:"POST",body:JSON.stringify({full_name:document.getElementById("name").value,email:document.getElementById("email").value,password:document.getElementById("pass").value})});toast("Account created");location.hash="#signin"}catch(e){document.getElementById("error").textContent=e.message}}
function signin(){navBar();app.innerHTML=`<div class="auth card"><h1>Sign in</h1><p class="muted">Signin</p><label>Email</label><input id="email" type="email" class="input"><label>Password</label><input id="pass" type="password" class="input"><button class="btn primary" onclick="doSignin()">Sign in</button><p>New user? <a href="#signup">Create account</a></p><div id="error" class="error"></div></div>`}
async function doSignin(){try{let d=await api("/auth/signin",{method:"POST",body:JSON.stringify({email:document.getElementById("email").value,password:document.getElementById("pass").value})});localStorage.setItem("token",d.access_token);location.hash="#home"}catch(e){document.getElementById("error").textContent=e.message}}
async function home(){if(!requireAuth())return;try{let u=await api("/auth/home");shell("Home",`<div class="card"><h2>Welcome, ${esc(u.full_name)} 👋</h2><p class="muted">You are signed in. Create and manage dynamic forms from the Forms page.</p><a class="btn primary" href="#forms">Open Form Management</a></div>`)}catch(e){logout()}}

async function forms(){if(!requireAuth())return;try{let fs=await api("/forms");shell("My Forms",`<div class="card"><div class="between"><input id="search" class="input" style="max-width:420px" placeholder="Search forms..." oninput="filterForms()"><a class="btn primary" href="#create">+ Create form</a></div></div><div id="formList" class="grid"></div>`);window.allForms=fs;renderForms(fs)}catch(e){err(e)}}
function renderForms(fs){document.getElementById("formList").innerHTML=fs.length?fs.map(f=>`<div class="card formcard"><div class="between"><h2>${esc(f.title)}</h2><span class="badge ${f.status}">${f.status}</span></div><p class="muted">Updated ${new Date(f.updated_at).toLocaleString()}</p><a class="btn" href="#builder/${f.id}">Open</a></div>`).join(""):`<div class="card empty">No forms yet. Create your first form.</div>`}
function filterForms(){let q=search.value.toLowerCase();renderForms(allForms.filter(f=>f.title.toLowerCase().includes(q)))}
function createForm(){if(!requireAuth())return;shell("Create Form",`<div class="card"><label>Form title</label><input id="title" class="input" placeholder="Job Application"><label>Description</label><textarea id="desc" class="input" rows="4"></textarea><div class="actions"><button class="btn primary" onclick="doCreate()">Create</button><a class="btn" href="#forms">Cancel</a></div></div>`)}
async function doCreate(){try{let f=await api("/forms",{method:"POST",body:JSON.stringify({title:document.getElementById("title").value,description:document.getElementById("desc").value||null})});toast("Form created");location.hash="#builder/"+f.id}catch(e){err(e)}}

let currentForm=null;
async function builder(id){if(!requireAuth())return;try{let f=await api("/forms/"+id);currentForm=f;shell("Form Builder",builderHTML(f));renderFields();await loadRules()}catch(e){err(e)}}
function builderHTML(f){return `<div class="card"><div class="between"><div><h2>${esc(f.title)}</h2><p class="muted">${esc(f.description||"")}</p><span class="badge ${f.status}">${f.status}</span> <span class="badge">Editing v${f.editing_version_number||1}</span></div><div class="actions"><button class="btn" onclick="editForm('${f.id}')">Edit form</button>${f.status!=="archived"?`<button class="btn" onclick="publishForm('${f.id}')">Publish</button>`:""}${f.status!=="archived"?`<button class="btn danger" onclick="archiveForm('${f.id}')">Archive</button>`:""}<a class="btn" href="#versions/${f.id}">Versions</a>${f.status==="published"?`<button class="btn primary" onclick="shareForm('${f.id}')">Share</button>`:""}</div></div></div>
<div class="card"><div class="between"><h2>Fields</h2><button class="btn primary" onclick="newField()">+ Add field</button></div><p class="muted">Drag-and-drop is represented by the Up/Down controls so the same display_order API is exercised.</p><div id="fields"></div></div>
<div class="card"><h2>Conditional rules</h2><p class="muted">Example: Experience = Yes → show Years of Experience.</p><div id="rules"></div><button class="btn" onclick="newRule()">+ Add rule</button></div>`}
async function refreshBuilder(){let f=await api("/forms/"+currentForm.id);currentForm=f;app.querySelector(".container").innerHTML=`<div class="between"><h1>Form Builder</h1></div>`+builderHTML(f);renderFields();renderRules()}
function renderFields(){let el=document.getElementById("fields"),fs=currentForm.fields||[];el.innerHTML=fs.length?fs.map((f,i)=>`<div class="field" draggable="true" data-index="${i}" ondragstart="dragStart(event)" ondragover="dragOver(event)" ondrop="dropField(event)" ondragend="dragEnd(event)"><div class="field-head"><div><strong>${esc(f.label)}</strong> <span class="badge">${esc(f.field_type)}</span> ${f.is_required?'<span class="badge">required</span>':''}<br><small class="muted">${esc(f.placeholder||"")}</small></div><div><button class="btn small" onclick="moveField(${i},-1)">↑</button><button class="btn small" onclick="moveField(${i},1)">↓</button><button class="btn small" onclick="editField('${f.id}')">Edit</button><button class="btn small danger" onclick="deleteField('${f.id}')">Delete</button></div></div>${(f.options||[]).length?`<p class="muted">Options: ${f.options.map(o=>esc(o.option_label)).join(", ")}</p>`:""}</div>`).join(""):`<div class="empty">No fields. Add Name, Email, Experience, Resume, etc.</div>`}
function renderRules(){let el=document.getElementById("rules"),rs=window.rules||[];el.innerHTML=rs.length?rs.map(r=>{let a=currentForm.fields.find(f=>f.id===r.trigger_field_id)?.label||"field",b=currentForm.fields.find(f=>f.id===r.target_field_id)?.label||"field";return `<div class="rule"><strong>${esc(a)}</strong> ${esc(r.operator)} "${esc(r.comparison_value)}" → ${esc(r.action)} <strong>${esc(b)}</strong> <button class="btn small danger" onclick="deleteRule('${r.id}')">Delete</button></div>`}).join(""):`<p class="muted">No rules yet.</p>`}
async function loadRules(){window.rules=await api("/forms/"+currentForm.id+"/rules");renderRules()}
async function newField(){let html=`<div class="card"><h2>Add field</h2>${fieldEditor()}</div>`;app.querySelector(".container").insertAdjacentHTML("afterbegin",html)}
function fieldEditor(f={}){let opts=(f.options||[]).map(o=>`${o.option_label}|${o.option_value}`).join("\n");return `<label>Label</label><input id="flabel" class="input" value="${esc(f.label||"")}"><label>Type</label><select id="ftype" class="input">${["text","email","number","date","dropdown","checkbox","file","textarea"].map(x=>`<option ${f.field_type===x?"selected":""}>${x}</option>`).join("")}</select><label>Placeholder</label><input id="fph" class="input" value="${esc(f.placeholder||"")}"><label><input id="freq" type="checkbox" ${f.is_required?"checked":""}> Required</label><label>Validation JSON (optional)</label><input id="fval" class="input" placeholder='{"min":0,"max":100}' value='${esc(f.validation_config?JSON.stringify(f.validation_config):"")}'> <label>Options (one <code>label|value</code> per line)</label><textarea id="fopts" class="input" rows="4">${esc(opts)}</textarea><div class="actions"><button class="btn primary" onclick="${f.id?`saveField('${f.id}')`:"saveNewField()"}">Save</button><button class="btn" onclick="this.closest('.card').remove()">Cancel</button></div>`}
function fieldPayload(){let validation=null;if(fval.value.trim())try{validation=JSON.parse(fval.value)}catch(e){throw Error("Validation JSON is invalid")}let options=fopts.value.split("\n").map(x=>x.trim()).filter(Boolean).map((x,i)=>{let [a,...b]=x.split("|");return {option_label:a,option_value:b.join("|")||a,display_order:i}});return {label:flabel.value,field_type:ftype.value,placeholder:fph.value||null,is_required:freq.checked,validation_config:validation,options:options.length?options:null}}
async function saveNewField(){try{await api("/forms/"+currentForm.id+"/fields",{method:"POST",body:JSON.stringify(fieldPayload())});toast("Field added");await builder(currentForm.id)}catch(e){err(e)}}
function editField(id){let f=currentForm.fields.find(x=>x.id===id);let d=document.createElement("div");d.className="card";d.innerHTML=`<h2>Edit field</h2>${fieldEditor(f)}`;app.querySelector(".container").prepend(d)}
async function saveField(id){try{await api("/fields/"+id,{method:"PUT",body:JSON.stringify(fieldPayload())});toast("Field updated");await builder(currentForm.id)}catch(e){err(e)}}
async function deleteField(id){if(!confirm("Delete this field?"))return;try{await api("/fields/"+id,{method:"DELETE"});await builder(currentForm.id)}catch(e){err(e)}}
async function moveField(i,delta){let fs=[...currentForm.fields],j=i+delta;if(j<0||j>=fs.length)return;[fs[i],fs[j]]=[fs[j],fs[i]];try{await api("/forms/"+currentForm.id+"/reorder-fields",{method:"PATCH",body:JSON.stringify({order:fs.map((f,k)=>({field_id:f.id,display_order:k}))})});await builder(currentForm.id)}catch(e){err(e)}}
let dragIndex=null;
function dragStart(e){dragIndex=Number(e.currentTarget.dataset.index);e.currentTarget.classList.add("dragging");e.dataTransfer.effectAllowed="move"}
function dragOver(e){e.preventDefault();e.currentTarget.classList.add("dropzone")}
function dragEnd(e){e.currentTarget.classList.remove("dragging","dropzone");document.querySelectorAll(".field").forEach(x=>x.classList.remove("dropzone"))}
async function dropField(e){e.preventDefault();let to=Number(e.currentTarget.dataset.index);if(dragIndex===null||dragIndex===to)return;let fs=[...currentForm.fields],m=fs.splice(dragIndex,1)[0];fs.splice(to,0,m);try{await api("/forms/"+currentForm.id+"/reorder-fields",{method:"PATCH",body:JSON.stringify({order:fs.map((f,k)=>({field_id:f.id,display_order:k}))})});await builder(currentForm.id)}catch(x){err(x)}finally{dragIndex=null}}
function editForm(id){let f=currentForm;app.querySelector(".container").insertAdjacentHTML("afterbegin",`<div class="card"><h2>Edit form</h2><label>Title</label><input id="etitle" class="input" value="${esc(f.title)}"><label>Description</label><textarea id="edesc" class="input">${esc(f.description||"")}</textarea><button class="btn primary" onclick="saveForm('${id}')">Save</button></div>`)}
async function saveForm(id){try{await api("/forms/"+id,{method:"PUT",body:JSON.stringify({title:etitle.value,description:edesc.value||null})});await builder(id)}catch(e){err(e)}}
async function archiveForm(id){if(!confirm("Archive this form? It will stop public access."))return;try{await api("/forms/"+id+"/archive",{method:"PATCH"});await builder(id)}catch(e){err(e)}}
async function publishForm(id){if(!confirm("Publish the current draft?"))return;try{await api("/forms/"+id+"/publish",{method:"POST"});toast("Published");await builder(id)}catch(e){err(e)}}
async function shareForm(id){try{let d=await api("/forms/"+id+"/generate-link",{method:"POST"});let url=location.origin+"/form/"+d.slug;app.insertAdjacentHTML("beforeend",`<div class="modal" id="shareModal"><div class="modalbox"><h2>Share Form</h2><p class="muted">Published version ${d.form_version_number}</p><input id="shareUrl" class="input" value="${esc(url)}" readonly><div class="actions"><button class="btn primary" onclick="copyShare()">Copy Link</button><a class="btn" href="${esc(url)}" target="_blank">Open Form</a><button class="btn" onclick="document.getElementById('shareModal').remove()">Close</button></div></div></div>`)}catch(e){err(e)}}
async function copyShare(){let x=document.getElementById("shareUrl");await navigator.clipboard.writeText(x.value);toast("Link copied")}
function newRule(){let fs=currentForm.fields||[];if(fs.length<2)return toast("Add at least two fields first");app.querySelector(".container").insertAdjacentHTML("afterbegin",`<div class="card"><h2>Add conditional rule</h2><label>When field</label><select id="rtrigger" class="input">${fs.map(f=>`<option value="${f.id}">${esc(f.label)}</option>`).join("")}</select><label>Operator</label><select id="rop" class="input"><option value="equals">equals</option><option value="not_equals">not equals</option><option value="contains">contains</option></select><label>Value</label><input id="rvalue" class="input"><label>Action</label><select id="raction" class="input"><option value="show">show</option><option value="hide">hide</option></select><label>Target field</label><select id="rtarget" class="input">${fs.map(f=>`<option value="${f.id}">${esc(f.label)}</option>`).join("")}</select><button class="btn primary" onclick="saveRule()">Save rule</button></div>`)}
async function saveRule(){try{await api("/forms/"+currentForm.id+"/rules",{method:"POST",body:JSON.stringify({trigger_field_id:rtrigger.value,operator:rop.value,comparison_value:rvalue.value,target_field_id:rtarget.value,action:raction.value})});toast("Rule added");await builder(currentForm.id);await loadRules()}catch(e){err(e)}}
async function deleteRule(id){try{await api("/forms/rules/"+id,{method:"DELETE"});await builder(currentForm.id);await loadRules()}catch(e){err(e)}}

async function versions(id){if(!requireAuth())return;try{let vs=await api("/forms/"+id+"/versions");shell("Version History",`<div class="card"><a class="btn" href="#builder/${id}">← Builder</a></div>${vs.map(v=>`<div class="card"><div class="between"><h2>Version ${v.version_number}</h2><span class="badge ${v.is_active?"published":""}">${v.is_active?"ACTIVE":"Draft/old"}</span></div><p class="muted">${v.published_at?"Published "+new Date(v.published_at).toLocaleString():"Not published"}</p><a class="btn" href="#version/${id}/${v.version_number}">View details</a></div>`).join("")}`)}catch(e){err(e)}}
async function versionDetail(id,n){if(!requireAuth())return;try{let v=await api(`/forms/${id}/versions/${n}`);shell(`Version ${n}`,`<div class="card"><a class="btn" href="#versions/${id}">← Version history</a><span class="badge ${v.is_active?"published":""}">${v.is_active?"ACTIVE":"READ ONLY"}</span></div><div class="card"><h2>Fields</h2>${v.fields.map(f=>`<div class="field"><strong>${esc(f.label)}</strong> — ${esc(f.field_type)} ${f.is_required?"(required)":""}</div>`).join("")}</div><div class="card"><h2>Rules</h2>${v.rules?.length?v.rules.map(r=>`<div class="rule">${esc(r.operator)} "${esc(r.comparison_value)}" → ${esc(r.action)}</div>`).join(""):"No rules"}</div>`)}catch(e){err(e)}}

async function publicPage(slug){navBar();try{let f=await api("/public/forms/"+slug);let start=Date.now();app.innerHTML=`<div class="container public"><div class="card"><h1>${esc(f.title)}</h1><p class="muted">${esc(f.description||"")}</p><form id="publicForm">${f.fields.map(fieldHTML).join("")}<button class="btn primary" type="submit">Submit</button></form></div></div>`;window.publicData=f;document.getElementById("publicForm").onsubmit=async e=>{e.preventDefault();let values={};f.fields.forEach(x=>{let els=document.querySelectorAll(`[data-field="${x.id}"]`);if(x.field_type==="checkbox")values[x.id]=[...els].filter(y=>y.checked).map(y=>y.value);else values[x.id]=els[0]?.value??""});try{let d=await api("/public/forms/"+slug+"/submit",{method:"POST",body:JSON.stringify({values,completion_time_seconds:Math.floor((Date.now()-start)/1000)})});app.querySelector(".card").innerHTML=`<div class="success"><h2>Thank you!</h2><p>${esc(d.message)}</p><p>Response ID: ${esc(d.response_id)}</p></div>`}catch(e){toast(e.message)}};applyRules()}catch(e){app.innerHTML=`<div class="container"><div class="card"><h1>Form unavailable</h1><p class="error">${esc(e.message)}</p></div></div>`}}
function fieldHTML(f){let input="";let req=f.is_required?"required":"";if(f.field_type==="textarea")input=`<textarea class="input" data-field="${f.id}" placeholder="${esc(f.placeholder||"")}" ${req}></textarea>`;else if(["dropdown"].includes(f.field_type))input=`<select class="input" data-field="${f.id}" ${req}><option value="">Select...</option>${(f.options||[]).map(o=>`<option value="${esc(o.option_value)}">${esc(o.option_label)}</option>`).join("")}</select>`;else if(f.field_type==="checkbox")input=(f.options||[]).map(o=>`<label><input type="checkbox" data-field="${f.id}" value="${esc(o.option_value)}"> ${esc(o.option_label)}</label>`).join("");else if(f.field_type==="file")input=`<input class="input" type="file" data-field="${f.id}" ${req}>`;else input=`<input class="input" type="${["text","email","number","date"].includes(f.field_type)?f.field_type:"text"}" data-field="${f.id}" placeholder="${esc(f.placeholder||"")}" ${req}>`;return `<div class="field" data-wrap="${f.id}"><label>${esc(f.label)} ${f.is_required?"*":""}</label>${input}</div>`}
function applyRules(){let rs=publicData.rules||[];rs.forEach(r=>{let trigger=document.querySelector(`[data-field="${r.trigger_field_id}"]`);let target=document.querySelector(`[data-wrap="${r.target_field_id}"]`);if(!trigger||!target)return;let fn=()=>{let val=trigger.type==="checkbox"?trigger.checked?trigger.value:"":trigger.value;let yes=r.operator==="equals"?val===r.comparison_value:r.operator==="not_equals"?val!==r.comparison_value:String(val).includes(r.comparison_value);target.classList.toggle("hidden",(r.action==="show")?!yes:yes)};trigger.addEventListener("input",fn);trigger.addEventListener("change",fn);fn()})}

async function route(){if(location.pathname.startsWith("/form/"))return publicPage(location.pathname.split("/")[2]);let p=location.hash.slice(1)||"home";if(p.startsWith("form/"))return publicPage(p.split("/")[1]);let [r,a,b]=p.split("/");if(r==="signup")return signup();if(r==="signin")return signin();if(r==="home")return home();if(r==="forms")return forms();if(r==="create")return createForm();if(r==="builder")return builder(a);if(r==="versions")return versions(a);if(r==="version")return versionDetail(a,b);return token()?home():signin()}
window.addEventListener("hashchange",route);route();
