"""add_uploaded_files_table

Revision ID: cac23723d3c8
Revises: 0001_initial
Create Date: 2026-09-08 21:36:13.594180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac23723d3c8'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.drop_constraint('conditional_rules_target_field_id_fkey', 'conditional_rules', type_='foreignkey')
    op.drop_constraint('conditional_rules_trigger_field_id_fkey', 'conditional_rules', type_='foreignkey')
    op.create_foreign_key(None, 'conditional_rules', 'fields', ['target_field_id'], ['id'])
    op.create_foreign_key(None, 'conditional_rules', 'fields', ['trigger_field_id'], ['id'])
    op.drop_constraint('field_options_field_id_fkey', 'field_options', type_='foreignkey')
    op.create_foreign_key(None, 'field_options', 'fields', ['field_id'], ['id'])
    op.drop_constraint('fields_form_version_id_fkey', 'fields', type_='foreignkey')
    op.create_foreign_key(None, 'fields', 'form_versions', ['form_version_id'], ['id'])
    op.drop_constraint('form_share_links_slug_key', 'form_share_links', type_='unique')
    op.drop_constraint('form_share_links_form_version_id_fkey', 'form_share_links', type_='foreignkey')
    op.create_foreign_key(None, 'form_share_links', 'form_versions', ['form_version_id'], ['id'])
    op.drop_constraint('uq_form_version_number', 'form_versions', type_='unique')
    op.drop_index('ix_forms_created_by', table_name='forms')
    op.drop_constraint('response_values_submission_id_fkey', 'response_values', type_='foreignkey')
    op.create_foreign_key(None, 'response_values', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'response_values', type_='foreignkey')
    op.create_foreign_key('response_values_submission_id_fkey', 'response_values', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_forms_created_by', 'forms', ['created_by'], unique=False)
    op.create_unique_constraint('uq_form_version_number', 'form_versions', ['form_id', 'version_number'])
    op.drop_constraint(None, 'form_share_links', type_='foreignkey')
    op.create_foreign_key('form_share_links_form_version_id_fkey', 'form_share_links', 'form_versions', ['form_version_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('form_share_links_slug_key', 'form_share_links', ['slug'])
    op.drop_constraint(None, 'fields', type_='foreignkey')
    op.create_foreign_key('fields_form_version_id_fkey', 'fields', 'form_versions', ['form_version_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'field_options', type_='foreignkey')
    op.create_foreign_key('field_options_field_id_fkey', 'field_options', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'conditional_rules', type_='foreignkey')
    op.drop_constraint(None, 'conditional_rules', type_='foreignkey')
    op.create_foreign_key('conditional_rules_trigger_field_id_fkey', 'conditional_rules', 'fields', ['trigger_field_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('conditional_rules_target_field_id_fkey', 'conditional_rules', 'fields', ['target_field_id'], ['id'], ondelete='CASCADE')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
